import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

import { getAllCategories } from "@/lib/data/category";
import type { Category } from "@/lib/generated/prisma";
import type React from "react";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const categories = await getAllCategories();

	if (!categories) {
		return null;
	}

	return (
		<html lang="en">
			<body className="flex flex-col font-serif justify-center antialiased ">
				<Navbar categories={categories} />
				{children}
			</body>
		</html>
	);
}
